# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(717, 832)
        self.textline = QtGui.QLabel(Form)
        self.textline.setGeometry(QtCore.QRect(40, 30, 96, 16))
        self.textline.setObjectName(_fromUtf8("textline"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 615, 171))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.okButton = QtGui.QPushButton(self.groupBox)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.gridLayout_4.addWidget(self.okButton, 1, 2, 1, 1)
        self.loadButton = QtGui.QPushButton(self.groupBox)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.gridLayout_4.addWidget(self.loadButton, 0, 2, 1, 1)
        self.inputLine = QtGui.QLineEdit(self.groupBox)
        self.inputLine.setObjectName(_fromUtf8("inputLine"))
        self.gridLayout_4.addWidget(self.inputLine, 0, 1, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.gridLayout_4)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 220, 657, 195))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.choose_light = QtGui.QLabel(self.groupBox_4)
        self.choose_light.setObjectName(_fromUtf8("choose_light"))
        self.gridLayout_2.addWidget(self.choose_light, 0, 0, 1, 1)
        self.port = QtGui.QComboBox(self.groupBox_4)
        self.port.setObjectName(_fromUtf8("port"))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.port, 0, 1, 1, 1)
        self.light_collect = QtGui.QPushButton(self.groupBox_4)
        self.light_collect.setObjectName(_fromUtf8("light_collect"))
        self.gridLayout_2.addWidget(self.light_collect, 0, 2, 1, 1)
        self.reset = QtGui.QPushButton(self.groupBox_4)
        self.reset.setObjectName(_fromUtf8("reset"))
        self.gridLayout_2.addWidget(self.reset, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.change_red = QtGui.QLabel(self.groupBox_4)
        self.change_red.setObjectName(_fromUtf8("change_red"))
        self.gridLayout.addWidget(self.change_red, 0, 0, 1, 1)
        self.red_Slider = QtGui.QSlider(self.groupBox_4)
        self.red_Slider.setMaximum(1200)
        self.red_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.red_Slider.setObjectName(_fromUtf8("red_Slider"))
        self.gridLayout.addWidget(self.red_Slider, 0, 1, 1, 1)
        self.red_light = QtGui.QLabel(self.groupBox_4)
        self.red_light.setObjectName(_fromUtf8("red_light"))
        self.gridLayout.addWidget(self.red_light, 0, 2, 1, 1)
        self.change_green = QtGui.QLabel(self.groupBox_4)
        self.change_green.setObjectName(_fromUtf8("change_green"))
        self.gridLayout.addWidget(self.change_green, 1, 0, 1, 1)
        self.green_Slider = QtGui.QSlider(self.groupBox_4)
        self.green_Slider.setMaximum(1000)
        self.green_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.green_Slider.setObjectName(_fromUtf8("green_Slider"))
        self.gridLayout.addWidget(self.green_Slider, 1, 1, 1, 1)
        self.green_light = QtGui.QLabel(self.groupBox_4)
        self.green_light.setObjectName(_fromUtf8("green_light"))
        self.gridLayout.addWidget(self.green_light, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.textline.setText(_translate("Form", "请发送串口信息：", None))
        self.groupBox.setTitle(_translate("Form", "静态显示：改变获取的图像文件夹", None))
        self.label.setText(_translate("Form", "请选择文件夹：", None))
        self.okButton.setText(_translate("Form", "确认", None))
        self.loadButton.setText(_translate("Form", "选择", None))
        self.groupBox_4.setTitle(_translate("Form", "动态显示：调整背景光亮度", None))
        self.choose_light.setText(_translate("Form", "请选择光串口：", None))
        self.port.setItemText(0, _translate("Form", "com3", None))
        self.port.setItemText(1, _translate("Form", "com1", None))
        self.port.setItemText(2, _translate("Form", "com2", None))
        self.port.setItemText(3, _translate("Form", "com4", None))
        self.port.setItemText(4, _translate("Form", "com5", None))
        self.port.setItemText(5, _translate("Form", "com6", None))
        self.port.setItemText(6, _translate("Form", "com7", None))
        self.port.setItemText(7, _translate("Form", "com8", None))
        self.port.setItemText(8, _translate("Form", "com9", None))
        self.port.setItemText(9, _translate("Form", "com10", None))
        self.port.setItemText(10, _translate("Form", "com11", None))
        self.port.setItemText(11, _translate("Form", "com12", None))
        self.port.setItemText(12, _translate("Form", "com13", None))
        self.port.setItemText(13, _translate("Form", "com14", None))
        self.port.setItemText(14, _translate("Form", "com15", None))
        self.port.setItemText(15, _translate("Form", "com16", None))
        self.light_collect.setText(_translate("Form", "背景光数据统计", None))
        self.reset.setText(_translate("Form", "重测", None))
        self.change_red.setText(_translate("Form", "红光光强调节：", None))
        self.red_light.setText(_translate("Form", "0.0", None))
        self.change_green.setText(_translate("Form", "绿光光强调节：", None))
        self.green_light.setText(_translate("Form", "0.0", None))

